module Ascii where

-- | paintHangman gibt das zur Fehleranzahl passende Bild aus
paintHangman :: Num a => a -> IO ()
paintHangman mistakes 

                  | mistakes==1 = do
                                  putStrLn "     " 
                                  putStrLn "      "   
                                  putStrLn "     "       
                                  putStrLn "      "       
                                  putStrLn "      "        
                                  putStrLn "      "         
                                  putStrLn "      "         
                                  putStrLn "     "  
                                  putStrLn "    / \\   "
                                  putStrLn "   /   \\ "
                                  putStrLn "  /     \\"
                  | mistakes==2 = do
                                  putStrLn "     | " 
                                  putStrLn "     | "   
                                  putStrLn "     | "       
                                  putStrLn "     | "       
                                  putStrLn "     | "        
                                  putStrLn "     | "         
                                  putStrLn "     | "         
                                  putStrLn "     | "       
                                  putStrLn "    / \\  "     
                                  putStrLn "   /   \\"
                                  putStrLn "  /     \\"
                                  
                  | mistakes==3 = do
                                  putStrLn "     ___________"
                                  putStrLn "     |    "
                                  putStrLn "     |  "
                                  putStrLn "     |   " 
                                  putStrLn "     |  " 
                                  putStrLn "     |  " 
                                  putStrLn "     |  "
                                  putStrLn "     |  "  
                                  putStrLn "     |  " 
                                  putStrLn "    / \\   " 
                                  putStrLn "   /   \\ "
                                  putStrLn "  /     \\"
                 | mistakes==4 = do
                                  putStrLn "     _____________"
                                  putStrLn "     |  /   "
                                  putStrLn "     | /  "
                                  putStrLn "     |    "
                                  putStrLn "     |     "
                                  putStrLn "     |   " 
                                  putStrLn "     |   "   
                                  putStrLn "     |   "
                                  putStrLn "     |   "
                                  putStrLn "    / \\  "
                                  putStrLn "   /   \\"
                                  putStrLn "  /     \\   "              
                 | mistakes==5 = do  
                                  putStrLn "     _____________"
                                  putStrLn "     |   /       |"
                                  putStrLn "     | /        / \\"
                                  putStrLn "     |          \\ /"
                                  putStrLn "     |   "
                                  putStrLn "     |  "
                                  putStrLn "     |  "
                                  putStrLn "     |  "
                                  putStrLn "     |      "
                                  putStrLn "    / \\     "
                                  putStrLn "   /   \\"
                                  putStrLn "  /     \\    "
                 | mistakes==6 = do   
                                  putStrLn "     _____________"
                                  putStrLn "     |   /       |"
                                  putStrLn "     | /        / \\"
                                  putStrLn "     |          \\ /"
                                  putStrLn "     |           |" 
                                  putStrLn "     |           |"
                                  putStrLn "     |           |"
                                  putStrLn "     |  "      
                                  putStrLn "     |  "     
                                  putStrLn "    / \\ "     
                                  putStrLn "   /   \\"
                                  putStrLn "  /     \\ "
                 | mistakes==7 = do   
                                  putStrLn "     _____________"
                                  putStrLn "     |   /       |"
                                  putStrLn "     | /        / \\"
                                  putStrLn "     |          \\ /"
                                  putStrLn "     |           |" 
                                  putStrLn "     |           |"
                                  putStrLn "     |           |"
                                  putStrLn "     |          /" 
                                  putStrLn "     |         / "  
                                  putStrLn "    / \\       / "    
                                  putStrLn "   /   \\"
                                  putStrLn "  /     \\ "                 
                 | mistakes==8 = do    
                                  putStrLn "     _____________"
                                  putStrLn "     |   /       |"
                                  putStrLn "     | /        / \\"
                                  putStrLn "     |          \\ /"
                                  putStrLn "     |           |"
                                  putStrLn "     |           |"
                                  putStrLn "     |           |"
                                  putStrLn "     |          / \\"
                                  putStrLn "     |         /   \\"
                                  putStrLn "    / \\       /     \\"
                                  putStrLn "   /   \\"
                                  putStrLn "  /     \\"                 
                 | mistakes==9 = do    
                                  putStrLn "     _____________"
                                  putStrLn "     |   /       |"
                                  putStrLn "     | /        / \\"
                                  putStrLn "     |          \\ /"
                                  putStrLn "     |         \\ |" 
                                  putStrLn "     |          \\|"
                                  putStrLn "     |           |"
                                  putStrLn "     |          / \\"
                                  putStrLn "     |         /   \\"
                                  putStrLn "    / \\       /     \\"
                                  putStrLn "   /   \\"
                                  putStrLn "  /     \\"
                 | mistakes==10 = do 
                                  putStrLn "     _____________"
                                  putStrLn "     |   /       |"
                                  putStrLn "     | /        / \\"
                                  putStrLn "     |          \\ /"
                                  putStrLn "     |    _|_    |"
                                  putStrLn "     |     |    /|\\"
                                  putStrLn "     |     |   / | \\"
                                  putStrLn "     |          / \\"
                                  putStrLn "     |         |   |"
                                  putStrLn "    / \\        |   |"
                                  putStrLn "   /   \\"
                                  putStrLn "  /     \\ " 
                                  
                 | otherwise =  do
                                  putStrLn "     " 
                                  putStrLn "      "   
                                  putStrLn "     "       
                                  putStrLn "      "       
                                  putStrLn "      "        
                                  putStrLn "      "         
                                  putStrLn "      "         
                                  putStrLn "     "  
                                  putStrLn "   "
                                  putStrLn " "
                                  putStrLn "  "